server:
  port: 8765

spring:
  application:
    name: book
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: KdC&+ozwE9Hq
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat.max-active: 20
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
