spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: KdC&+ozwE9Hq
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat.max-active: 20
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  thymeleaf:
    cache: false
  kafka:
    bootstrap-servers: localhost:9092
    # 生产者
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # 消费者
    consumer:
      group-id: my-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: 192.168.202.128
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: bookstore
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: qian1974051900
  graphql:
    graphiql:
      enabled: true